/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author jocej
 */
public class Hospital extends javax.swing.JFrame {

    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        llApPaterno = new javax.swing.JLabel();
        lbApMa = new javax.swing.JLabel();
        lbNombre3 = new javax.swing.JLabel();
        lbNombre4 = new javax.swing.JLabel();
        lbNombre5 = new javax.swing.JLabel();
        lbNombre6 = new javax.swing.JLabel();
        lbNombre7 = new javax.swing.JLabel();
        lbNombre8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox<>();
        fechaN = new com.toedter.calendar.JDateChooser();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        fechaIngreso = new com.toedter.calendar.JDateChooser();
        txtHoraIngreso = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        reloj1 = new Componente2.Reloj();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbNombre1 = new javax.swing.JLabel();
        lbNombre2 = new javax.swing.JLabel();
        lbNombre9 = new javax.swing.JLabel();
        lbNombre10 = new javax.swing.JLabel();
        lbNombre11 = new javax.swing.JLabel();
        cbBuscar = new javax.swing.JComboBox<>();
        txtAlergias = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        rbAlta = new javax.swing.JRadioButton();
        rbHospitalizacion = new javax.swing.JRadioButton();
        reloj2 = new Componente2.Reloj();
        btnGuardarRegistro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbNombre12 = new javax.swing.JLabel();
        cbBuscarEgreso = new javax.swing.JComboBox<>();
        lbNombre13 = new javax.swing.JLabel();
        fechaEgreso = new com.toedter.calendar.JDateChooser();
        lbNombre14 = new javax.swing.JLabel();
        txtHoraEgreso = new javax.swing.JTextField();
        lbNombre15 = new javax.swing.JLabel();
        txtObservacionesEgreso = new javax.swing.JTextField();
        btnGuardarEgreso = new javax.swing.JButton();
        reloj3 = new Componente2.Reloj();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbNombre16 = new javax.swing.JLabel();
        cbBuscarEgreso1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reloj5 = new Componente2.Reloj();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setBackground(new java.awt.Color(13, 71, 161));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(21, 101, 192));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 101, 192));
        jLabel1.setText("INGRESO DE PACIENTES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 102, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        lbNombre.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 101, 0, 0);
        jPanel2.add(lbNombre, gridBagConstraints);

        llApPaterno.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        llApPaterno.setText("Apellido Paterno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 101, 0, 0);
        jPanel2.add(llApPaterno, gridBagConstraints);

        lbApMa.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbApMa.setText("Apellido Materno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 101, 0, 0);
        jPanel2.add(lbApMa, gridBagConstraints);

        lbNombre3.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre3.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 101, 0, 0);
        jPanel2.add(lbNombre3, gridBagConstraints);

        lbNombre4.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre4.setText("Fecha de nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 101, 0, 0);
        jPanel2.add(lbNombre4, gridBagConstraints);

        lbNombre5.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre5.setText("Edad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 101, 0, 0);
        jPanel2.add(lbNombre5, gridBagConstraints);

        lbNombre6.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre6.setText("Peso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 101, 0, 0);
        jPanel2.add(lbNombre6, gridBagConstraints);

        lbNombre7.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre7.setText("Fecha de Ingreso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 101, 0, 0);
        jPanel2.add(lbNombre7, gridBagConstraints);

        lbNombre8.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre8.setText("Hora Ingreso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 101, 0, 0);
        jPanel2.add(lbNombre8, gridBagConstraints);

        txtNombre.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 65, 0, 0);
        jPanel2.add(txtNombre, gridBagConstraints);

        txtPaterno.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtPaterno.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 0);
        jPanel2.add(txtPaterno, gridBagConstraints);

        txtMaterno.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtMaterno.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 0);
        jPanel2.add(txtMaterno, gridBagConstraints);

        cbGenero.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        cbGenero.setForeground(new java.awt.Color(38, 50, 56));
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno", "Femenino", "Masculino" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 121, 0, 0);
        jPanel2.add(cbGenero, gridBagConstraints);

        fechaN.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 65, 0, 0);
        jPanel2.add(fechaN, gridBagConstraints);

        txtEdad.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 137, 0, 0);
        jPanel2.add(txtEdad, gridBagConstraints);

        txtPeso.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtPeso.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 137, 0, 0);
        jPanel2.add(txtPeso, gridBagConstraints);

        fechaIngreso.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 65, 0, 0);
        jPanel2.add(fechaIngreso, gridBagConstraints);

        txtHoraIngreso.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtHoraIngreso.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 3, 0, 0);
        jPanel2.add(txtHoraIngreso, gridBagConstraints);

        btnGuardar.setBackground(new java.awt.Color(72, 187, 120));
        btnGuardar.setFont(new java.awt.Font("Swis721 BT", 3, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 54, 25, 0);
        jPanel2.add(btnGuardar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 59, 0, 33);
        jPanel2.add(reloj1, gridBagConstraints);

        jTabbedPane1.addTab("Ingreso", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(21, 101, 192));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 101, 192));
        jLabel2.setText("REGISTRO DE PACIENTE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 105, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        lbNombre1.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre1.setText("Buscar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 88, 0, 0);
        jPanel3.add(lbNombre1, gridBagConstraints);

        lbNombre2.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre2.setText("Alergias:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 88, 0, 0);
        jPanel3.add(lbNombre2, gridBagConstraints);

        lbNombre9.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre9.setText("Observaciones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 88, 0, 0);
        jPanel3.add(lbNombre9, gridBagConstraints);

        lbNombre10.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre10.setText("Diagnostico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 88, 0, 0);
        jPanel3.add(lbNombre10, gridBagConstraints);

        lbNombre11.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre11.setText("Salida:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 88, 0, 0);
        jPanel3.add(lbNombre11, gridBagConstraints);

        cbBuscar.setBackground(new java.awt.Color(96, 125, 139));
        cbBuscar.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        cbBuscar.setForeground(new java.awt.Color(255, 255, 255));
        cbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 39, 0, 0);
        jPanel3.add(cbBuscar, gridBagConstraints);

        txtAlergias.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtAlergias.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 277;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 39, 0, 0);
        jPanel3.add(txtAlergias, gridBagConstraints);

        txtObservaciones.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 277;
        gridBagConstraints.ipady = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 0, 0);
        jPanel3.add(txtObservaciones, gridBagConstraints);

        txtDiagnostico.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtDiagnostico.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 277;
        gridBagConstraints.ipady = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 0, 0);
        jPanel3.add(txtDiagnostico, gridBagConstraints);

        buttonGroup1.add(rbAlta);
        rbAlta.setForeground(new java.awt.Color(76, 175, 80));
        rbAlta.setText("Alta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 82, 0, 0);
        jPanel3.add(rbAlta, gridBagConstraints);

        buttonGroup1.add(rbHospitalizacion);
        rbHospitalizacion.setForeground(new java.awt.Color(229, 57, 53));
        rbHospitalizacion.setText("Hospitalización");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 8, 0, 0);
        jPanel3.add(rbHospitalizacion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 76, 0, 53);
        jPanel3.add(reloj2, gridBagConstraints);

        btnGuardarRegistro.setBackground(new java.awt.Color(72, 187, 120));
        btnGuardarRegistro.setFont(new java.awt.Font("Swis721 BT", 3, 14)); // NOI18N
        btnGuardarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarRegistro.setText("Guardar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 113, 31, 0);
        jPanel3.add(btnGuardarRegistro, gridBagConstraints);

        jTabbedPane1.addTab("Registro", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(21, 101, 192));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 101, 192));
        jLabel3.setText("EGRESO DE PACIENTE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 137, 0, 0);
        jPanel4.add(jLabel3, gridBagConstraints);

        lbNombre12.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre12.setText("Buscar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 95, 0, 0);
        jPanel4.add(lbNombre12, gridBagConstraints);

        cbBuscarEgreso.setBackground(new java.awt.Color(96, 125, 139));
        cbBuscarEgreso.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        cbBuscarEgreso.setForeground(new java.awt.Color(255, 255, 255));
        cbBuscarEgreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 10, 0, 0);
        jPanel4.add(cbBuscarEgreso, gridBagConstraints);

        lbNombre13.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre13.setText("Fecha de Egreso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 95, 0, 0);
        jPanel4.add(lbNombre13, gridBagConstraints);

        fechaEgreso.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 96, 0, 0);
        jPanel4.add(fechaEgreso, gridBagConstraints);

        lbNombre14.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre14.setText("Hora de Egreso:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 95, 0, 0);
        jPanel4.add(lbNombre14, gridBagConstraints);

        txtHoraEgreso.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtHoraEgreso.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 162, 0, 0);
        jPanel4.add(txtHoraEgreso, gridBagConstraints);

        lbNombre15.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre15.setText("Observaciones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 95, 0, 0);
        jPanel4.add(lbNombre15, gridBagConstraints);

        txtObservacionesEgreso.setFont(new java.awt.Font("Swis721 BT", 0, 14)); // NOI18N
        txtObservacionesEgreso.setForeground(new java.awt.Color(38, 50, 56));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 258;
        gridBagConstraints.ipady = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        jPanel4.add(txtObservacionesEgreso, gridBagConstraints);

        btnGuardarEgreso.setBackground(new java.awt.Color(72, 187, 120));
        btnGuardarEgreso.setFont(new java.awt.Font("Swis721 BT", 3, 14)); // NOI18N
        btnGuardarEgreso.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEgreso.setText("Guardar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 93, 110, 0);
        jPanel4.add(btnGuardarEgreso, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 79, 0, 51);
        jPanel4.add(reloj3, gridBagConstraints);

        jTabbedPane1.addTab("Egreso", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel4.setBackground(new java.awt.Color(21, 101, 192));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 101, 192));
        jLabel4.setText("LISTA DE PACIENTES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 106, 0, 0);
        jPanel5.add(jLabel4, gridBagConstraints);

        lbNombre16.setFont(new java.awt.Font("Swis721 BT", 2, 14)); // NOI18N
        lbNombre16.setText("Buscar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 61, 0, 0);
        jPanel5.add(lbNombre16, gridBagConstraints);

        cbBuscarEgreso1.setBackground(new java.awt.Color(96, 125, 139));
        cbBuscarEgreso1.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        cbBuscarEgreso1.setForeground(new java.awt.Color(255, 255, 255));
        cbBuscarEgreso1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 45, 0, 0);
        jPanel5.add(cbBuscarEgreso1, gridBagConstraints);

        jTable1.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 564;
        gridBagConstraints.ipady = 243;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(29, 46, 120, 48);
        jPanel5.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 282, 0, 0);
        jPanel5.add(reloj5, gridBagConstraints);

        jTabbedPane1.addTab("Vista", jPanel5);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarEgreso;
    private javax.swing.JButton btnGuardarRegistro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbBuscar;
    private javax.swing.JComboBox<String> cbBuscarEgreso;
    private javax.swing.JComboBox<String> cbBuscarEgreso1;
    private javax.swing.JComboBox<String> cbGenero;
    private com.toedter.calendar.JDateChooser fechaEgreso;
    private com.toedter.calendar.JDateChooser fechaIngreso;
    private com.toedter.calendar.JDateChooser fechaN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbApMa;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lbNombre10;
    private javax.swing.JLabel lbNombre11;
    private javax.swing.JLabel lbNombre12;
    private javax.swing.JLabel lbNombre13;
    private javax.swing.JLabel lbNombre14;
    private javax.swing.JLabel lbNombre15;
    private javax.swing.JLabel lbNombre16;
    private javax.swing.JLabel lbNombre2;
    private javax.swing.JLabel lbNombre3;
    private javax.swing.JLabel lbNombre4;
    private javax.swing.JLabel lbNombre5;
    private javax.swing.JLabel lbNombre6;
    private javax.swing.JLabel lbNombre7;
    private javax.swing.JLabel lbNombre8;
    private javax.swing.JLabel lbNombre9;
    private javax.swing.JLabel llApPaterno;
    private javax.swing.JRadioButton rbAlta;
    private javax.swing.JRadioButton rbHospitalizacion;
    private Componente2.Reloj reloj1;
    private Componente2.Reloj reloj2;
    private Componente2.Reloj reloj3;
    private Componente2.Reloj reloj5;
    private javax.swing.JTextField txtAlergias;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtHoraEgreso;
    private javax.swing.JTextField txtHoraIngreso;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtObservacionesEgreso;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
